apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agconn

resources:
  - namespace.yaml
  - service-account.yaml
  - configmap.yaml
  - web-deployment.yaml
  - admin-deployment.yaml
  - api-deployment.yaml
  - email-worker-deployment.yaml
  - sms-worker-deployment.yaml
  - flc-verifier-deployment.yaml
  - audit-cronjobs.yaml
  - ingress.yaml
