import { fetchReportRuns } from '@/lib/reports-api';

export const metadata = { title: 'Past exports — AgConn Admin' };
export const dynamic = 'force-dynamic';

type SearchParams = Record<string, string | string[] | undefined>;

function buildQs(sp: SearchParams): string {
  const params = new URLSearchParams();
  if (typeof sp['reportType'] === 'string') params.set('reportType', sp['reportType']);
  if (typeof sp['from'] === 'string') params.set('from', sp['from']);
  if (typeof sp['to'] === 'string') params.set('to', sp['to']);
  params.set('limit', '50');
  return params.toString();
}

export default async function ReportRunsPage({
  searchParams,
}: {
  searchParams: Promise<SearchParams>;
}) {
  const sp = await searchParams;
  const result = await fetchReportRuns(buildQs(sp));
  const queued = sp['queued'] === '1';

  return (
    <div className="space-y-6">
      <div>
        <p className="eyebrow text-base-content/60">Platform / Reports</p>
        <h1 className="font-serif text-2xl font-medium tracking-tight">Past exports</h1>
        <p className="text-base-content/70 mt-1 max-w-2xl text-sm">
          Audit trail of every grant report generated by an admin. Archived exports
          stay re-downloadable as long as the audit log retains the row (7 years for
          placement data).
        </p>
      </div>

      {queued ? (
        <div className="alert alert-success">
          <span>
            Your export is on its way. The recipient will get an email with a
            24-hour download link, and the file is archived here for re-download.
          </span>
        </div>
      ) : null}

      {!result.ok ? (
        <div role="alert" className="alert alert-error">
          <span>
            {result.error.code} — {result.error.message}
          </span>
        </div>
      ) : result.data.runs.length === 0 ? (
        <div className="bg-base-100 border-base-300 text-base-content/70 rounded-box border p-8 text-center text-sm">
          No reports have been generated yet.
        </div>
      ) : (
        <div className="bg-base-100 border-base-300 overflow-hidden rounded-box border">
          <table className="table-zebra table">
            <thead className="bg-base-200">
              <tr>
                <th>Generated</th>
                <th>Report</th>
                <th>Format</th>
                <th className="text-right">Rows</th>
                <th>By</th>
                <th>Filters</th>
                <th className="text-right"></th>
              </tr>
            </thead>
            <tbody>
              {result.data.runs.map((r) => {
                const f = r.filters as Record<string, unknown>;
                const start = typeof f['start'] === 'string' ? f['start'] : '';
                const end = typeof f['end'] === 'string' ? f['end'] : '';
                const counties = Array.isArray(f['counties']) ? f['counties'].join(', ') : '';
                return (
                  <tr key={r.id}>
                    <td className="font-mono text-xs">
                      {r.generatedAt.replace('T', ' ').slice(0, 19)}
                    </td>
                    <td className="text-sm capitalize">{r.reportType}</td>
                    <td className="font-mono text-xs uppercase">{r.format}</td>
                    <td className="text-right font-mono text-xs tabular-nums">
                      {r.rowCount}
                    </td>
                    <td className="font-mono text-xs">{r.generatedBy}</td>
                    <td className="text-xs">
                      <span className="font-mono">
                        {start && end ? `${start} → ${end}` : ''}
                      </span>
                      {counties ? (
                        <span className="text-base-content/60 ml-2">{counties}</span>
                      ) : null}
                    </td>
                    <td className="text-right">
                      {r.hasArchive ? (
                        <a
                          href={`/api/reports/runs/${r.id}/download`}
                          className="btn btn-ghost btn-xs"
                        >
                          Download
                        </a>
                      ) : (
                        <span className="text-base-content/40 text-xs">—</span>
                      )}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
