import { getTranslations } from 'next-intl/server';
import { Link } from '@/i18n/navigation';

export default async function AdminReportsIndex() {
  const t = await getTranslations('admin.reports');
  const tFallback = (k: string, en: string) => {
    const out = t(k, { default: '' });
    return out && out.length > 0 ? out : en;
  };

  return (
    <div className="space-y-6">
      <div>
        <h2 className="font-serif text-2xl font-medium">
          {tFallback('index.title', 'Grant reports')}
        </h2>
        <p className="text-base-content/70 mt-1 max-w-2xl text-sm">
          {tFallback(
            'index.subtitle',
            'WIOA / CalJOBS-aligned exports for grantees. Field labels match the most recent CDFA / EDD reporting templates. Every export is logged.',
          )}
        </p>
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        <ReportCard
          href="/admin/reports/placement"
          title={tFallback('placement.card.title', 'Placement report')}
          desc={tFallback(
            'placement.card.desc',
            'Hires within a date range, joined with the worker’s most recent completed training. CSV or XLSX, anonymized participant IDs by default.',
          )}
        />
        <ReportCard
          href="/admin/reports/runs"
          title={tFallback('runs.card.title', 'Past exports')}
          desc={tFallback(
            'runs.card.desc',
            'Audit trail of every report generated by an admin: filters used, row count, format, and timestamp.',
          )}
        />
      </div>
    </div>
  );
}

function ReportCard({ href, title, desc }: { href: string; title: string; desc: string }) {
  return (
    <Link
      href={href}
      className="bg-base-100 border-base-300 hover:border-primary block rounded-2xl border p-5 transition-colors"
    >
      <h3 className="font-serif text-lg font-medium">{title}</h3>
      <p className="text-base-content/70 mt-2 text-sm">{desc}</p>
    </Link>
  );
}
