import type { Tx } from '@agconn/db';
import { ComplianceItemStatus } from '@agconn/db';

// audit-required:exempt — these helpers run inside the onboarding transaction
// (employer.flc.submitted is the parent audit). Seeding deterministic default
// rows for a brand-new employer is part of that single user-initiated action;
// emitting per-row audits would explode the audit log without adding evidence.

type DefaultItem = {
    category: string;
    itemKey: string;
    label: string;
    status?: ComplianceItemStatus;
    details?: string;
};

// New employers seed in a "needs confirmation" state — most items can't
// truthfully be marked compliant on day one (no I-9s yet, no plan documents
// uploaded, no PUR filings, etc.). Items default to `warn` so the dashboard
// reflects reality and the operator has a real punch list to work through.
// H-2A items default to `ok` because they're only meaningful for H-2A program
// participants; non-H-2A employers shouldn't see an inflated "fail" count for
// rules that don't apply to them.
const DEFAULT_COMPLIANCE_ITEMS: DefaultItem[] = [
    // Worker documentation
    { category: 'documentation', itemKey: 'i9_on_file', label: 'I-9 forms on file', status: ComplianceItemStatus.warn, details: 'Confirm a process for collecting and storing I-9s.' },
    { category: 'documentation', itemKey: 'w4_collected', label: 'W-4s collected', status: ComplianceItemStatus.warn, details: 'Confirm W-4s are collected from every new hire.' },
    { category: 'documentation', itemKey: 'i9_expiring', label: 'I-9s expiring within 30 days', status: ComplianceItemStatus.ok, details: 'No expirations on file.' },

    // Worker safety (Cal/OSHA)
    { category: 'safety', itemKey: 'heat_plan', label: 'Heat illness prevention plan', status: ComplianceItemStatus.warn, details: 'Required by Cal/OSHA §3395 — upload your written plan.' },
    { category: 'safety', itemKey: 'wps_training', label: 'Pesticide handler training (WPS)', status: ComplianceItemStatus.warn, details: 'Document training for any pesticide handlers on staff.' },
    { category: 'safety', itemKey: 'covid_plan', label: 'COVID-19 prevention plan', status: ComplianceItemStatus.warn, details: 'Upload your written plan or mark as no longer required.' },

    // Wage & hour
    { category: 'wage_hour', itemKey: 'piece_breaks', label: 'Piece-rate paid breaks tracked', status: ComplianceItemStatus.warn, details: 'Confirm AB 1513 paid-rest-period tracking is in place.' },
    { category: 'wage_hour', itemKey: 'overtime', label: 'Overtime calculations', status: ComplianceItemStatus.warn, details: 'Confirm 2025 phase-in: 8h daily / 40h weekly thresholds.' },
    { category: 'wage_hour', itemKey: 'wage_stmts', label: 'Itemized wage statements', status: ComplianceItemStatus.ok, details: 'Auto-generated by AGCONN payroll.' },

    // Pesticide records
    { category: 'pesticide', itemKey: 'pur_records', label: 'Application records (PUR)', status: ComplianceItemStatus.warn, details: 'File Pesticide Use Reports monthly with the county Ag Commissioner.' },
    { category: 'pesticide', itemKey: 'noi_filing', label: 'Notice of Intent (NOI)', status: ComplianceItemStatus.warn, details: 'Submit NOIs to CDPR before restricted-material applications.' },

    // H-2A program — start as `ok` for non-H-2A employers; H-2A participants
    // should mark them `warn` and document compliance as they ramp up.
    { category: 'h2a', itemKey: 'aewr_rate', label: 'AEWR rate compliance', status: ComplianceItemStatus.ok, details: 'Adverse Effect Wage Rate — only applies to H-2A program participants.' },
    { category: 'h2a', itemKey: 'housing_insp', label: 'Housing inspection', status: ComplianceItemStatus.ok, details: 'Annual per 20 CFR 655.122 — only applies to H-2A program participants.' },
    { category: 'h2a', itemKey: 'three_quarter', label: '3/4 guarantee tracking', status: ComplianceItemStatus.ok, details: 'Only applies to H-2A program participants.' },
];

export async function seedDefaultComplianceItems(
    tx: Tx,
    tenantId: string,
    employerId: string,
): Promise<void> {
    await tx.complianceItem.createMany({
        data: DEFAULT_COMPLIANCE_ITEMS.map((item) => ({
            tenantId,
            employerId: employerId,
            category: item.category,
            itemKey: item.itemKey,
            label: item.label,
            status: item.status ?? ComplianceItemStatus.ok,
            details: item.details ?? null,
        })),
        skipDuplicates: true,
    });
}

export async function seedInitialPayrollPeriod(
    tx: Tx,
    tenantId: string,
    employerId: string,
): Promise<void> {
    // Build a Mon–Sun pay period covering the current week, with pay date the
    // following Friday (matches "runs Friday" copy in the design).
    const now = new Date();
    const dow = now.getUTCDay(); // 0=Sun
    const offset = dow === 0 ? -6 : 1 - dow;
    const start = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
    start.setUTCDate(start.getUTCDate() + offset);
    const end = new Date(start);
    end.setUTCDate(start.getUTCDate() + 6);
    const pay = new Date(end);
    pay.setUTCDate(end.getUTCDate() + 5); // Friday after Sunday end

    const existing = await tx.payrollPeriod.findFirst({
        where: { tenantId, employerId: employerId, startDate: start },
    });
    if (existing) return;

    await tx.payrollPeriod.create({
        data: {
            tenantId,
            employerId: employerId,
            startDate: start,
            endDate: end,
            payDate: pay,
        },
    });
}
