import Link from 'next/link';

export const metadata = { title: 'Reports — AgConn Admin' };

export default function AdminReportsIndex() {
  return (
    <div className="space-y-6">
      <div>
        <p className="eyebrow text-base-content/60">Platform</p>
        <h1 className="font-serif text-2xl font-medium tracking-tight">Grant reports</h1>
        <p className="text-base-content/70 mt-1 max-w-2xl text-sm">
          WIOA / CalJOBS-aligned exports for grantees. Field labels follow Title I
          conventions. Every export is logged and re-downloadable.
        </p>
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        <ReportCard
          href="/reports/placement"
          title="Placement report"
          desc="Hires within a date range, joined with the worker's most recent completed training. CSV or XLSX, anonymized participant IDs by default."
        />
        <ReportCard
          href="/reports/runs"
          title="Past exports"
          desc="Audit trail of every report generated by an admin: filters used, row count, format, timestamp, and re-download link."
        />
      </div>
    </div>
  );
}

function ReportCard({
  href,
  title,
  desc,
}: {
  href: string;
  title: string;
  desc: string;
}) {
  return (
    <Link
      href={href}
      className="bg-base-100 border-base-300 hover:border-primary block rounded-box border p-5 transition-colors"
    >
      <h3 className="font-serif text-lg font-medium">{title}</h3>
      <p className="text-base-content/70 mt-2 text-sm">{desc}</p>
    </Link>
  );
}
