// Reseed compliance items for an existing employer to the current defaults.
// Use after changing seed-defaults so already-onboarded test tenants reflect
// the new starting state instead of the historical one.
//
// Usage (from repo root):
//   pnpm --filter @agconn/db tsx scripts/reseed-compliance.ts <user-email>

import { config as loadEnv } from 'dotenv';
loadEnv({ path: '../../.env' });

const STATUS_BY_KEY: Record<string, 'ok' | 'warn' | 'fail'> = {
    i9_on_file: 'warn',
    w4_collected: 'warn',
    i9_expiring: 'ok',
    heat_plan: 'warn',
    wps_training: 'warn',
    covid_plan: 'warn',
    piece_breaks: 'warn',
    overtime: 'warn',
    wage_stmts: 'ok',
    pur_records: 'warn',
    noi_filing: 'warn',
    aewr_rate: 'ok',
    housing_insp: 'ok',
    three_quarter: 'ok',
};

const DETAILS_BY_KEY: Record<string, string> = {
    i9_on_file: 'Confirm a process for collecting and storing I-9s.',
    w4_collected: 'Confirm W-4s are collected from every new hire.',
    i9_expiring: 'No expirations on file.',
    heat_plan: 'Required by Cal/OSHA §3395 — upload your written plan.',
    wps_training: 'Document training for any pesticide handlers on staff.',
    covid_plan: 'Upload your written plan or mark as no longer required.',
    piece_breaks: 'Confirm AB 1513 paid-rest-period tracking is in place.',
    overtime: 'Confirm 2025 phase-in: 8h daily / 40h weekly thresholds.',
    wage_stmts: 'Auto-generated by AGCONN payroll.',
    pur_records: 'File Pesticide Use Reports monthly with the county Ag Commissioner.',
    noi_filing: 'Submit NOIs to CDPR before restricted-material applications.',
    aewr_rate: 'Adverse Effect Wage Rate — only applies to H-2A program participants.',
    housing_insp: 'Annual per 20 CFR 655.122 — only applies to H-2A program participants.',
    three_quarter: 'Only applies to H-2A program participants.',
};

async function main() {
    const email = process.argv[2];
    if (!email) {
        console.error('Usage: tsx reseed-compliance.ts <user-email>');
        process.exit(1);
    }

    const { prisma } = await import('../src/index.js');

    await prisma.$transaction(async (tx) => {
        await tx.$executeRawUnsafe(`SET LOCAL app.role = 'admin'`);

        const user = await tx.user.findFirst({
            where: { email: email.toLowerCase() },
        });
        if (!user) {
            console.error(`No user found with email ${email}`);
            process.exit(1);
        }
        if (!user.tenantId) {
            console.error(`User ${email} has no tenantId — not yet onboarded.`);
            process.exit(1);
        }

        const items = await tx.complianceItem.findMany({
            where: { tenantId: user.tenantId, employerId: user.id },
        });
        console.log(`Found ${items.length} compliance items for ${email} (tenant ${user.tenantId})`);

        let updated = 0;
        for (const item of items) {
            const newStatus = STATUS_BY_KEY[item.itemKey];
            const newDetails = DETAILS_BY_KEY[item.itemKey];
            if (!newStatus) continue;
            if (item.status === newStatus && item.details === newDetails) continue;
            await tx.complianceItem.update({
                where: { id: item.id },
                data: { status: newStatus, details: newDetails ?? null },
            });
            updated++;
        }
        console.log(`Updated ${updated} items.`);
    });

    await prisma.$disconnect();
}

main().catch((e) => {
    console.error(e);
    process.exit(1);
});
